language: cpp
cache: ccache
sudo: required
dist: trusty

os:
  - linux
env:
  - JOB=check_style

addons:
  apt:
    packages:
      - git
      - python
      - python-pip
      - python2.7-dev
      - clang-format-3.8

before_install:
  - sudo pip install -U virtualenv pre-commit pip

script:
  - if [[ "$JOB" == "check_style" ]]; then sudo ln -s /usr/bin/clang-format-3.8 /usr/bin/clang-format; fi
  - |
    function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
  - |
    timeout 600 .travis/${JOB}.sh # 10min timeout
    RESULT=$?; if [ $RESULT -eq 0 ] || [ $RESULT -eq 142 ]; then true; else exit 1; fi;

notifications:
  email:
    on_success: change
    on_failure: always
