language: cpp
cache: ccache
sudo: required
dist: trusty

os:
  - linux
env:
  global:
    - CMAKE_URL=https://cmake.org/files/v3.11/cmake-3.11.1-Linux-x86_64.tar.gz
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-6.0
      - ubuntu-toolchain-r-test
    packages:
      - git
      - python
      - python-pip
      - python2.7-dev
      - libc6-i386
      - clang-6.0
      - libclang-6.0
      - llvm-6.0
      - llvm-6.0-dev
      - curl

compiler:
  - clang
        
before_install:
  - sudo pip install -U virtualenv pre-commit pip
  # Download and install recent cmake
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      CMAKE_URL=${CMAKE_URL}
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

#install:
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
#  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-6.0" CC="clang-6.0"; fi

before_script:
  - |
    echo "cmake generate compile_commands.json for clang-tidy"
    ls -l -a
    clang-tidy -version 
    clang-format -version
script:
  - | 
    function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
  - |
    timeout 600 .travis/pre-commit-job.sh # 10min timeout
    RESULT=$?; if [ $RESULT -eq 0 ] || [ $RESULT -eq 142 ]; then true; else exit 1; fi;

notifications:
  email:
    on_success: change
    on_failure: always
