# Copyright (c) 2019 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
''' Collect op registry information. '''

from __future__ import print_function
import sys
import logging
from ast import RegisterLiteOpParser

if len(sys.argv) != 6:
    print("Error: parse_op_registry.py requires five inputs!")
    exit(1)
ops_list_path = sys.argv[1]
dest_header_path = sys.argv[2]
minops_list_path = sys.argv[3]
tailored = sys.argv[4]
with_extra = sys.argv[5]

# Generate .h path and .cc path
# dest_header_path is like ".../paddle_use_ops.h"
dest_cc_path = dest_header_path.replace('.h', '.cc')

header_lines = [
    '#pragma once',
    '#include "paddle_lite_factory_helper.h"',
    '',
]

paths = set()
for line in open(ops_list_path):
    paths.add(line.strip())

if tailored == "ON":
    minlines = set()
    with open(minops_list_path) as fd:
        for line in fd:
            minlines.add(line.strip())

# Collect all ops that are actually emitted
emitted_ops = []
for path in paths:
    str_info = open(path.strip()).read()
    op_parser = RegisterLiteOpParser(str_info)
    ops = op_parser.parse(with_extra)
    for op in ops:
        if tailored == "ON":
            if op not in minlines: continue
        out = "USE_LITE_OP(%s);" % op
        header_lines.append(out)
        emitted_ops.append(op)

# Append inline RegisterAllOps() guarded by #ifdef LITE_LAZY_REGISTER.
# generate_factory_helper.py resolves this block at build time.
header_lines.extend([
    '',
    '#ifdef LITE_LAZY_REGISTER',
    'namespace paddle {',
    'namespace lite {',
    'namespace detail {',
    '__attribute__((used)) inline void RegisterAllOps() {',
])
for op in emitted_ops:
    header_lines.append('  touch_op_%s();' % op)
header_lines.extend([
    '}',
    '}  // namespace detail',
    '}  // namespace lite',
    '}  // namespace paddle',
    '#endif  // LITE_LAZY_REGISTER',
])

# Generate .h file
with open(dest_header_path, 'w') as f:
    logging.info("write op header to %s" % dest_header_path)
    f.write('\n'.join(header_lines))

# Generate .cc file: weak empty fallback compiled into the SDK.
# Overridden at link time by the inline RegisterAllOps() from any consumer
# that #includes paddle_use_ops.h (e.g. MMLNative).
cc_lines = [
    '// Auto-generated by parse_op_registry.py - DO NOT EDIT',
    '// SDK weak-empty fallback for RegisterAllOps().',
    '// Overridden at link time by the inline version in paddle_use_ops.h.',
    '',
    '#ifdef LITE_LAZY_REGISTER',
    'namespace paddle {',
    'namespace lite {',
    'namespace detail {',
    '__attribute__((weak)) void RegisterAllOps() {}',
    '}  // namespace detail',
    '}  // namespace lite',
    '}  // namespace paddle',
    '#endif  // LITE_LAZY_REGISTER',
]

with open(dest_cc_path, 'w') as f:
    logging.info("write op source to %s" % dest_cc_path)
    f.write('\n'.join(cc_lines))
