repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    sha: v1.0.1
    hooks:
    -   id: remove-crlf
        files: ^(mobile/src/).*\.(md|py|mm|swift|java|c|cc|cxx|cpp|cu|h|hpp|hxx)$
        exclude: ^(lite/)
    -   id: remove-tabs
        files: ^(mobile/test/|mobile/src/).*\.(md|py|mm|swift|java|c|cc|cxx|cpp|cu|h|hpp|hxx)$
        exclude: ^(lite/)

-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: check-added-large-files
        exclude: ^(lite/)
    -   id: check-merge-conflict
        exclude: ^(lite/)
    -   id: check-symlinks
        exclude: ^(lite/)
    -   id: detect-private-key
        files: (?!.*tar.gz)^.*$ 
        exclude: ^(lite/)
    -   id: end-of-file-fixer
        files: ^(mobile/test/|mobile/src/).*\.(md|py|mm|swift|java|c|cc|cxx|cpp|h|hpp|hxx)$
        exclude: ^(lite/)
    -   id: trailing-whitespace
        files: ^(mobile/test/|mobile/src/).*\.(md|py|mm|swift|java|c|cc|cxx|cpp|h|hpp|hxx)$
        exclude: ^(lite/)

-   repo: local
    hooks:
    -   id: copyright
        name: copyright
        entry: python ./mobile/tools/pre-commit.hooks/copyright.hook
        language: system
        files: ^(mobile/test/|mobile/src/).*\.(c|cc|cxx|cpp|h|hpp|hxx|py)$
        exclude: (?!.*third_party)^.*$ | (?!.*book)^.*$ | ^(lite/)

-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        description: Format files with ClangFormat.
        entry: bash ./mobile/tools/pre-commit.hooks/clang-format.hook -i
        language: system
        files: ^(mobile/test/|mobile/src/).*\.(c|cc|cxx|cpp|h|hpp|hxx)$
        exclude: ^(lite/)

-   repo: local
    hooks:
    -   id: cpplint
        name: cpplint
        description: Check C++ code style using cpplint.
        entry: bash ./mobile/tools/pre-commit.hooks/cpplint.hook
        language: system
        files: ^(mobile/test/|mobile/src/).*\.(c|cc|cxx|cpp|h|hpp|hxx)$
        exclude: (?!.*third_party)^.*$ | (?!.*book)^.*$i | *\.pb\.cpp | ^(lite/)


#
#-   repo: local
#    hooks:
#    -   id: clang-tidy
#        name: clang-tidy
#        description: Check C++ code style using clang-tidy.
#        entry: bash ./tools/pre-commit.hooks/.clang-tidy.hook -i
#        language: system
#        files: (src).*\.(c|cc|cxx|cpp|h|hpp|hxx)$
