language: cpp
cache: ccache
sudo: required
dist: trusty

os:
  - linux

addons:
  apt:
    packages:
      - git
      - python
      - python-pip
      - python2.7-dev
      - libc6-i386
      - curl

compiler:
  - clang
        
before_install:
  - sudo pip install -U virtualenv pre-commit pip
  # Download and install recent cmake

script:
  - | 
    function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
  - |
    timeout 600 .travis/pre-commit-job.sh # 10min timeout
    RESULT=$?; if [ $RESULT -eq 0 ] || [ $RESULT -eq 142 ]; then true; else exit 1; fi;

notifications:
  email:
    on_success: change
    on_failure: always
