// Copyright (c) 2019 PaddlePaddle Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * Internal header for lazy registration.
 * This header is NOT part of the public API and should only be used
 * by light_api_impl.cc for calling RegisterAllOps/RegisterAllKernels.
 */

#pragma once

#ifdef LITE_LAZY_REGISTER

namespace paddle {
namespace lite {
namespace detail {

// Register all ops. Generated by parse_op_registry.py.
// Only available when LITE_LAZY_REGISTER is defined.
void RegisterAllOps();

// Register all kernels. Generated by parse_kernel_registry.py.
// Only available when LITE_LAZY_REGISTER is defined.
void RegisterAllKernels();

}  // namespace detail
}  // namespace lite
}  // namespace paddle

#endif  // LITE_LAZY_REGISTER
